# ----------------------------------
# TABLE OF CONTENTS
#
# 1. Site Settings - Controls the content that appears in the html metadata Title and Description attributes for site pages. The title attribute is used as the first part of the browser page title, i.e., "VA Digital Service Handbook - Page Title Here"
#
# 2. Ignore Everything Below This Line - content that follows control Jekyll and Github. Content Writers and Editors can ignore all of this.
#
# ----------------------------------

# 1. Site Settings
title: VA Digital Service Handbook

title_short: Digital Service Handbook

description: The VA Digital Service Handbook helps Veteran Affairs (VA) teams create great digital services that meet the Digital Service Standard for the Veteran Tools Platform.

tagline: Helping Veterans Affairs teams design, build, and launch great digital services that meet the <a title="Digital Service Standard" href="digital-standard">Digital Service Standard</a> for the Veteran Tools Platform.

contact-handbook:
  name: Elizabeth Hunt
  email: elizabeth.hunt@va.gov

slack:
  devsupport: devsupport-external  

vets-team: <i>Once you've been added to the VA Github organization, you'll be able to see this content.</i>

# ----------------------------------
# 2. IGNORE EVERYTHING BELOW THIS LINE
# ----------------------------------

# Navigation Menu
nav:
  menu-button: Menu
  skip_nav: Skip to main content

footer:
  org-title: Digital Service at VA
  va-org-title: part of VA OIT

# Additional Site Settings
image: /assets/img/logo/og-image.jpg
canonical_domain: department-of-veterans-affairs.github.io
url: https://department-of-veterans-affairs.github.io
baseurl: /va-digital-service-handbook


# Pages
collections:
  pages:
    output: true
    permalink: /:path/

# Build settings
kramdown:
  hard_wrap: true

# Defaults
defaults:
- scope:
    path: ""
  values:
    layout: base

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - LICENSE
  - CONTRIBUTING
  - README
  - vendor

sass:
    # Either :compressed or :expanded
    style: :compressed
    # Where you keep your scss files
    sass_dir: _sass
    # Where sass should look for other scss
    #load_paths:
      #- node_modules/uswds/src/stylesheets
      #- _sass/_variables.scss
      #- _sass/_main.scss
